### ISSUE TITLE
Datasource pass_password fails if value is not a string in yaml

### ISSUE THREAD

**Issue by mcanevet** [camptocamp/terraform-provider-pass#6]
The `pass_password` provider fails if the value of the yaml secret as something else than a string.
For example:
```yaml
mysecret
---
user: myuser
password: mysecret
foo: 1
```
Will fail with:
```
expected type 'string', got unconvertible type 'int'
```
The same problem occurs if the value is a map.
